# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  start: 
    desc: "Start the server"
    cmds:
      - go run ./cmd/grpc_auth/main.go --config=./config/local.yaml
  migrate:
    aliases: 
      - mig
    desc: "Run migrations"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/auth.db --migrations-path=./migrations

  migrate tests:
    aliases: 
      - migtest
    desc: "Run test migrations"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/auth.db --migrations-path=./tests/migrations --migrations-table=migrations_test